name: Update ChinaList-For-AdguardHome

on: workflow_dispatch

jobs:
  update_dns_list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
        chmod +x script.sh
        ./script.sh
    - name: Push changes
      run: |
        git add ChinaList.txt
        git commit -m "Update ChinaList.txt"
        git push https://$GITHUB_TOKEN@github.com/${{ secrets.USER_NAME }}/ChinaList-For-AdguardHome.git HEAD
